<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-POMS.Web-1e108764-6c1d-4c71-b419-bba3888d202b</UserSecretsId>
    
    <!-- Prevent Web Deploy and MSDeploy from deleting resources on publish -->
    <ExcludeFoldersFromDeployment>App_Data;wwwroot\uploads</ExcludeFoldersFromDeployment>
    <SkipExtraFilesOnServer>True</SkipExtraFilesOnServer>
  </PropertyGroup>

  <ItemGroup>
    <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.31" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.31" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\POMS.Data\POMS.Data.csproj" />
  </ItemGroup>

</Project>
